<div class="row mb-4">
    <div class="col-md-8">
        <strong>Order id#: <?php echo $jobOrder->job_order_id; ?></strong>
    </div>
    <div class="col-md-4">
        <span class="order-ship-to-label">Ship To:</span>
        <span class="order-customer-name"><?php echo $jobOrder->first_name . ' ' . $jobOrder->last_name; ?></span>
        <span class="order-address"> <?php echo $jobOrder->shipping_address1 . ' ' . $jobOrder->shipping_address2 . '' . $jobOrder->shipping_address3; ?></span>
        <span class="order-address"><?php echo $jobOrder->shipping_city; ?></span>
        <span class="order-address"><?php echo $jobOrder->shipping_state; ?></span>
        <span class="order-address"><?php echo $jobOrder->shipping_country; ?></span>
    </div>
</div>

<div class="cart-header mobile-hidden">
    <div class="row">
        <div class="col-md-3"><span class="pl-2">Product</span></div>
        <div class="col-md-3"></div>
        <div class="col-md-3 text-right pr-5">Quantity</div>
        <div class="col-md-3 text-right cart-price">Price</div>
    </div>
</div>

<?php 
    $subTotal = 0;
    $grandTotal = 0;
    foreach($items as $item ) { 
        $subTotal += $item['price'];
?>
<div class="cart-box" >
    <div class="row">
        <div class="col-md-3">
            <img class="img-fluid" src="<?php echo $this->basePath() . '/' . $item['product_thumbnail'];?>" alt=""/>
        </div>
        <div class="col-md-3">
            <h6 class="mb-3"><?php echo $item['product_name']; ?></h6>
            <p class="mb-2"><?php echo $item['product_desc']; ?></p>
            <span class="cart-product-price">$<?php echo number_format($item['unit_price'],2); ?> each</span>
        </div>
        <div class="col-md-3 text-right pr-5"><?php echo $item['qty']; ?></div>
        <div class="col-md-3 text-right pr-5">$ <?php echo number_format($item['price'],2); ?></div>
    </div>
</div>

<?php 
    } 

    $grandTotal = $jobOrder->shipping_total + $subTotal;
?>

<div class="total">
    <div class="row">
        <div class="ml-md-auto col-md-4 pr-5">
            <div class="row mb-3">
                <div class="col-md-6 col-sm-12">Subtotal</div>
                <div class="col-md-6 col-sm-12 currency-label">$ <?php echo number_format($subTotal,2);?></div>
            </div>
            <div class="row mb-5">
                <div class="col-md-6 col-sm-12">Shipping</div>
                <div class="col-md-6 col-sm-12 currency-label"><?php echo number_format($jobOrder->shipping_total,2); ?></div>
            </div>
            <div class="row mb-5 font-weight-bold text-primary">
                <div class="col-md-6">Grand Total</div>
                <div class="col-md-6 currency-label">$ <?php echo number_format($grandTotal,2);?></div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <a href="<?php echo $this->basePath('/');?>" class="btn btn-success btn-continue-shopping btn-block">Continue Shopping</a>
                </div>
            </div>
        </div>
    </div>
   
</div>