<?php $orderAction = $this->url('shipping-info');  ?>

<?php
    $shippingMethod = 'Ground';
    if(isset($post->shipping_method)) {
        $shippingMethod = $post->shipping_method;
    }
?>
<div class="page-subheader">
    <span>Shipping</span>
</div>

<div class="row justify-content-md-center">
    <div class="col-lg-8">
        <form action="<?= $orderAction; ?>" method="POST" class="form">
            <div class="form-group">
                <label for="shippingName">Name</label>
                <input type="text" id="shippingName" name="shipping_name" class="form-control" value="<?php echo isset($post->shipping_name) ? $post->shipping_name : ''; ?>" />
                <small class="text-danger"><?php echo (isset($errors[0]['shipping_name']['isEmpty'])) ? $errors[0]['shipping_name']['isEmpty'] : '';?></small>
                <small class="text-danger"><?php echo (isset($errors[0]['shipping_name']['stringLengthTooLong'])) ? $errors[0]['shipping_name']['stringLengthTooLong'] : '';?></small>
            </div>
            <div class="form-group">
                <label for="shippingAddress1">Address 1</label>
                <input type="text" id="shippingAddress1" name="shipping_address1" class="form-control" value="<?php echo isset($post->shipping_address1) ? $post->shipping_address1 : ''; ?>" />
                <small class="text-danger"><?php echo (isset($errors[0]['shipping_address1']['isEmpty'])) ? $errors[0]['shipping_address1']['isEmpty'] : '';?></small>
                <small class="text-danger"><?php echo (isset($errors[0]['shipping_address1']['stringLengthTooLong'])) ? $errors[0]['shipping_address1']['stringLengthTooLong'] : '';?></small>
            </div>
            <div class="form-group">
                <label for="shippingAddress2">Address 2</label>
                <input type="text" id="shippingAddress2" name="shipping_address2" class="form-control" value="<?php echo isset($post->shipping_address2) ? $post->shipping_address2 : ''; ?>" />
            </div>
            <div class="form-group">
                <label for="shippingAddress3">Address 3</label>
                <input type="text" id="shippingAddress3" name="shipping_address3" class="form-control"  value="<?php echo isset($post->shipping_address3) ? $post->shipping_address3 : ''; ?>" />
            </div>
            <div class="form-group">
                <label for="city">City</label>
                <input type="text" id="city" name="shipping_city" class="form-control" value="<?php echo isset($post->shipping_city) ? $post->shipping_city : ''; ?>" />
                <small class="text-danger"><?php echo (isset($errors[0]['shipping_city']['isEmpty'])) ? $errors[0]['shipping_city']['isEmpty'] : '';?></small>
                <small class="text-danger"><?php echo (isset($errors[0]['shipping_city']['stringLengthTooLong'])) ? $errors[0]['shipping_city']['stringLengthTooLong'] : '';?></small>
            </div>
            <div class="form-group">
                <label for="state">State</label>
                <input type="text" id="state" name="shipping_state" class="form-control" value="<?php echo isset($post->shipping_state) ? $post->shipping_state : ''; ?>"/>
                <small class="text-danger"><?php echo (isset($errors[0]['shipping_state']['isEmpty'])) ? $errors[0]['shipping_state']['isEmpty'] : '';?></small>
                <small class="text-danger"><?php echo (isset($errors[0]['shipping_state']['stringLengthTooLong'])) ? $errors[0]['shipping_state']['stringLengthTooLong'] : '';?></small>
            </div>
            <div class="form-group">
                <label for="country">Country</label>
                <input type="text" id="country" name="shipping_country" class="form-control" value="<?php echo isset($post->shipping_country) ? $post->shipping_country : ''; ?>"/>
                <small class="text-danger"><?php echo (isset($errors[0]['shipping_country']['isEmpty'])) ? $errors[0]['shipping_country']['isEmpty'] : '';?></small>
                <small class="text-danger"><?php echo (isset($errors[0]['shipping_country']['stringLengthTooLong'])) ? $errors[0]['shipping_country']['stringLengthTooLong'] : '';?></small>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="custom-control custom-radio mb-3">
                        <input type="radio" id="groundRadio" name="shipping_method" class="custom-control-input shippingMethod" value="Ground" <?php echo $shippingMethod == 'Ground' ? 'checked' : '';?>/>
                        <label class="custom-control-label" for="groundRadio"><span class="shipping-type">Ground Shipping</span></label>
                    </div>
                </div>
                <div class="col-md-6">$ <?php echo $shippingRates['Ground']; ?></div>
            </div>
            
            <div class="row">
                <div class="col-md-6">
                    <div class="custom-control custom-radio mb-3">
                        <input type="radio" id="expeditedRadio" name="shipping_method" class="custom-control-input shippingMethod" value="Expedited" <?php echo $shippingMethod == 'Expedited' ? 'checked' : '';?> />
                        <label class="custom-control-label" for="expeditedRadio"><span class="shipping-type">Expedited Shipping</span></label>
                    </div>
                </div>
                <div class="col-md-6">$ <?php echo $shippingRates['Expedited']; ?></div>
            </div>

            <input type="hidden" id="shippingTotal" name="shipping_total" value="<?php echo $shippingRates['Ground']?>"/>

            <div class="text-center">
                <button type="submit" class="btn btn-success btn-shipping">Continue</button>
            </div>
        </form> 
    </div>
<div class="row justify-content-md-center">

<script>
var shippingRates = <?php echo json_encode($shippingRates); ?>;
$(document).ready(function(){
    $(".shippingMethod").click(function(){
        $("#shippingTotal").val(shippingRates[$(this).val()]);
    });
});
</script>